name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            git config --global --add safe.directory /www/wwwroot/covernomads-dev.mspgulf.com/backend/nheil

            cd /www/wwwroot/covernomads-dev.mspgulf.com/backend/nheil

            # Ensure Git uses SSH instead of HTTPS (run this once manually too)
            git remote set-url origin git@github.com:YOUR_USERNAME/YOUR_REPO.git

            git fetch origin main
            git reset --hard origin/main

            npm install
            npm install -g pm2

            pm2 reload covernomads-backend || pm2 start server.js --name covernomads-backend

            echo "✅ Deployment completed successfully on $(date)"
