name: Auto Deploy Node.js Site to aaPanel

on:
  push:
    branches:
      - main  # Change to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Go to project folder
            cd /www/wwwroot/covernomads-dev.mspgulf.com/backend/nheil
            
            # Pull latest code
            git fetch --all
            git reset --hard origin/main
            
            # Install dependencies
            npm install
            
            # Build project (if using React/Vue/Next/etc.)
            npm run build
            
            # Restart Node.js app if using PM2
            pm2 restart example || pm2 start npm --name "npm" -- start

            echo "Deployment completed at $(date)"
